
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/library")
exports.getFilteredCelebs = /*#__PURE__*/ $mkFactory("SELECT *\nFROM  celeb\nWHERE\nCONCAT(firstName,\" \", lastname) LIKE CONCAT('%', ?, '%')\nLIMIT ? OFFSET ?;")
