
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
exports.countFilteredCelebs = require("./countFilteredCelebs.edge.js").countFilteredCelebs
exports.getFilteredCelebs = require("./getFilteredCelebs.edge.js").getFilteredCelebs
exports.selectSortedMoviesByRatings = require("./selectSortedMoviesByRatings.edge.js").selectSortedMoviesByRatings
