
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
exports.countFilteredCelebs = require("./countFilteredCelebs.js").countFilteredCelebs
exports.getFilteredCelebs = require("./getFilteredCelebs.js").getFilteredCelebs
exports.selectSortedMoviesByRatings = require("./selectSortedMoviesByRatings.js").selectSortedMoviesByRatings
