
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/library")
exports.selectSortedMoviesByRatings = /*#__PURE__*/ $mkFactory("SELECT movie.id\nFROM movie\nINNER JOIN moviedata\nON movie.moviedataId = moviedata.id\n\nINNER JOIN _genretomovie\nON movie.id = _genretomovie.B\n\nINNER JOIN genre\nON _genretomovie.A = genre.id\n\n\nWHERE\nmoviedata.title LIKE CONCAT('%', ?, '%')\nAND\ngenre.id IN (?)\n\nGROUP BY movie.id\n\nHAVING COUNT(DISTINCT genre.id) = ?\n")
